image: node:8

before_script:
  - npm install

stages:
  - test
  - publish

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm run coverage

publish:
  stage: publish
  script:
    - npm publish
  dependencies:
    - test
  only:
    - master
  when: manual
